-- Count of customers + sample of 10 first orders for audit/logging
WITH FIRSTS AS (
  SELECT
    CUSTOMER_ID,
    ORDER_ID,
    ORDER_DATE,
    ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE, ORDER_ID) AS RN
  FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
)
SELECT COUNT(*) AS TOTAL_CUSTOMERS_WITH_FIRST_ORDER
FROM FIRSTS
WHERE RN = 1;

-- Sample 10 first orders to keep report concise
WITH FIRSTS AS (
  SELECT
    CUSTOMER_ID,
    ORDER_ID,
    ORDER_DATE,
    ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE, ORDER_ID) AS RN
  FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
)
SELECT CUSTOMER_ID, ORDER_ID, ORDER_DATE
FROM FIRSTS
WHERE RN = 1
ORDER BY ORDER_DATE
LIMIT 10;
