WITH CUSTOMER_SALES AS (
  SELECT CUSTOMER_ID, SUM(SALES) AS TOTAL_SALES
  FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
  GROUP BY CUSTOMER_ID
)
SELECT
  CUSTOMER_ID,
  TOTAL_SALES,
  RANK() OVER (ORDER BY TOTAL_SALES DESC) AS CUSTOMER_RANK
FROM CUSTOMER_SALES
QUALIFY CUSTOMER_RANK <= 10
ORDER BY CUSTOMER_RANK;
