WITH CUSTOMER_SALES AS (
  SELECT CUSTOMER_ID, SUM(SALES) AS TOTAL_SALES
  FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
  GROUP BY CUSTOMER_ID
),
LABELED AS (
  SELECT
    CUSTOMER_ID,
    TOTAL_SALES,
    NTILE(4) OVER (ORDER BY TOTAL_SALES DESC) AS SALES_QUARTILE
  FROM CUSTOMER_SALES
)
SELECT
  SALES_QUARTILE,
  COUNT(*)              AS CUSTOMER_COUNT,
  SUM(TOTAL_SALES)      AS TOTAL_SALES_IN_QUARTILE,
  AVG(TOTAL_SALES)      AS AVG_SALES_PER_CUSTOMER
FROM LABELED
GROUP BY SALES_QUARTILE
ORDER BY SALES_QUARTILE;
