WITH MONTHLY AS (
  SELECT
    DATE_TRUNC('MONTH', ORDER_DATE) AS MONTH_START,
    SUM(SALES) AS SALES_PER_MONTH
  FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
  GROUP BY 1
)
SELECT
  MONTH_START,
  SALES_PER_MONTH,
  SUM(SALES_PER_MONTH) OVER (
    ORDER BY MONTH_START
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS RUNNING_TOTAL_SALES
FROM MONTHLY
ORDER BY MONTH_START;
