-- Day 14: Standardize Customer Names (case formatting)
SELECT 
  CUSTOMER_ID,
  CUSTOMER_NAME,
  UPPER(CUSTOMER_NAME)   AS NAME_UPPER,
  LOWER(CUSTOMER_NAME)   AS NAME_LOWER,
  INITCAP(CUSTOMER_NAME) AS NAME_PROPER
FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
LIMIT 50;