WITH daily AS (
  SELECT
    ORDER_DATE::DATE                          AS ORDER_DATE,
    DATE_TRUNC('MONTH', ORDER_DATE)::DATE     AS MONTH_START,
    SUM(SALES)                                AS DAILY_SALES
  FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
  GROUP BY ORDER_DATE::DATE, DATE_TRUNC('MONTH', ORDER_DATE)::DATE
)
SELECT
  MONTH_START,
  ORDER_DATE,
  DAILY_SALES,
  SUM(DAILY_SALES) OVER (
    PARTITION BY MONTH_START
    ORDER BY ORDER_DATE
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS MTD_SALES
FROM daily
ORDER BY MONTH_START, ORDER_DATE;