WITH daily AS (
  SELECT
    ORDER_DATE::DATE AS ORDER_DATE,
    SUM(SALES)       AS DAILY_SALES
  FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
  GROUP BY ORDER_DATE::DATE
)
SELECT
  ORDER_DATE,
  DAILY_SALES,
  AVG(DAILY_SALES) OVER (
    ORDER BY ORDER_DATE
    RANGE BETWEEN INTERVAL '30 DAY' PRECEDING AND CURRENT ROW
  ) AS AVG_SALES_30D
FROM daily
ORDER BY ORDER_DATE;
