WITH daily AS (
  SELECT
    ORDER_DATE::DATE AS ORDER_DATE,
    SUM(SALES)       AS DAILY_SALES
  FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
  GROUP BY ORDER_DATE::DATE
)
SELECT
  ORDER_DATE,
  DAILY_SALES,
  SUM(DAILY_SALES) OVER (
    ORDER BY ORDER_DATE
    RANGE BETWEEN INTERVAL '6 DAY' PRECEDING AND CURRENT ROW
  ) AS SALES_LAST_7_DAYS
FROM daily
ORDER BY ORDER_DATE;
