SELECT
  CUSTOMER_ID,
  ORDER_ID,
  ORDER_DATE,
  SALES,
  LAG(SALES, 1) OVER (
    PARTITION BY CUSTOMER_ID
    ORDER BY ORDER_DATE, ORDER_ID
  ) AS PREVIOUS_ORDER_SALES
FROM "SUPERSTOREDB"."PUBLIC"."SUPERSTORE_SALES"
ORDER BY CUSTOMER_ID, ORDER_DATE, ORDER_ID;